language: python

matrix:
    include:

        # - os: osx
        #   language: generic
        #   env:
        #     - TOXENV=py36
        #     - COVERALLS_PARALLEL=true

        - os: linux
          python: 3.6
          env:
            - TOXENV=py36
            - COVERALLS_PARALLEL=true

        # - os: linux
        #   python: 3.7
        #   dist: xenial
        #   sudo: true
        #   env:
        #     - TOXENV=py37
        #     - COVERALLS_PARALLEL=true

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
  - pip install sphinx
  - pip install sphinx_rtd_theme

script:
  - make docs
  # - make test

after_success:
  - coveralls

notifications:
  - webhooks: https://coveralls.io/webhook
  - email: false
